import { createBlueprintModule } from '$lib/blueprint';
import { getSupabase } from '@supabase/auth-helpers-sveltekit';
import type { Actions } from './$types';

export const actions: Actions = {
	create: async (event) => {
		const formData = await event.request.formData();

		const { session, supabaseClient } = await getSupabase(event);

		if (session?.user?.id) {
			const name = formData.get('name') as unknown as string;
			// Some fields are generated by the database, so we don't need to include them in the insert
			// eslint-disable-next-line @typescript-eslint/no-unused-vars
			const { id, created_at, ...blueprintModule } = createBlueprintModule(session.user.id, name);

			supabaseClient
				.from('blueprints')
				// eslint-disable-next-line @typescript-eslint/no-explicit-any
				.insert([blueprintModule as any])
				.then((res) => {
					console.log(res);
				});
		}
	}
};
